### ISSUE TITLE
[Discussion Needed] about Forking private project

### ISSUE THREAD

**Issue by oshimaryo** [mozilla-japan/gitfab2#1117]
Private Project を Fork すると、
親がプライベートでも、子はパブリックにできてしまう。

いまのところすぐに動ける回避策としては

* 親がプライベートの場合、子はプライベートにしかできない（親がパブリックにすると、子もパブリックにできる）
* 気にしない

**Comment by ToruHagihara** [comment]
[気にしない]が良いと思います。

理由：
- プライベートな親をフォークできるのは、それ自体を閲覧可能な限られたメンバのみである。
- 親があとからパブリック→プライベートに変更された時にも子との矛盾が発生するが、これは回避できない。

現状の仕様のままで良いとおもいます。
（プライベートな親をフォークした直後は子はプライベートとなる）

**Comment by oshimaryo** [comment]
ありがとうございます。
そうしましょう。
このイシューを閉じます。
