### ISSUE TITLE
NewLine char does not work in card

### ISSUE THREAD

**Issue by ToruHagihara** [mozilla-japan/gitfab2#1146]
Stateの編集画面で改行の混じったテキストを登録した場合、
編集後画面で改行が反映される場合とされない場合がある。

- 改行される例(Converted to `<br>` tag)
 - Enterを２回連続入力
 - ctrl+Enter

- 改行されない例(Ignored)
 - Enterを一回入力

再度、編集画面を開くと、データとして改行は保持されているようです。
カード内のテキストの改行はどのように扱われる想定でしょうか？

<img width="409" alt="2015-07-17 15 09 26" src="https://cloud.githubusercontent.com/assets/13010899/8741557/f4193c76-2c95-11e5-88c3-43642314d8b2.png">
<img width="500" alt="2015-07-17 15 09 09" src="https://cloud.githubusercontent.com/assets/13010899/8741558/f44b57c4-2c95-11e5-8d42-e02949e9e4b7.png">
---
OS X 10.10.4
safari 8.0.7

**Comment by ToruHagihara** [comment]
改行する、されないがわかりにくく、思ったレイアウトに編集しにくかったのでIssueにあげさせていただきました。

**Comment by oshimaryo** [comment]
Issue作成ありがとうございます。
確認したところ、SafariだけでなくChromeでも同様で、WebKit系のブラウザで起こる問題のようです。
原因は、フォームで改行時に挿入されるタグがFirefoxの場合は<br>なのに対し、Webkitでは<div>が挿入される、という処理の違いのようです。 

* Chrome
<img width="1160" alt="2015-07-22 14 35 27" src="https://cloud.githubusercontent.com/assets/980357/8818669/3dc74056-307f-11e5-9200-0f588a0ca3e8.png">

* Firefox
<img width="1160" alt="2015-07-22 14 35 27" src="https://cloud.githubusercontent.com/assets/980357/8818674/4ceeca9a-307f-11e5-895a-8688c20ce2b5.png">

Fabbleでは入力されたものを表示するときにセキュリティと表示の統一（たとえばフォントサイズをバラバラにはしない）の観点からSanitizeしており、下のリンク先で挙げられたもの以外のタグは取り除いた状態で描画されます。
https://github.com/mozilla-japan/gitfab2/blob/develop/config%2Finitializers%2Fsanitize.rb#L5

**Comment by oshimaryo** [comment]
下のプルリクエストでは、とりあえず、今回のケースへの対処をします。

ただし、たとえばGoogle Docsから貼り付けたような場合にはフォームと表示に差がある問題を解決するためには、タグの他にDOMに直接書かれたstyle attributeを受け入れる必要があり、それを受け入れると表示の統一性が損なわれる問題が避けられないので、今の所対処しないこととします。

**Comment by ToruHagihara** [comment]
対応ありがとうございます。
現在の仕様の方針として以下のように理解しました。
フォームで入力した改行→改行させる
外部からのコピー＆ペーストで挿入したデータ→元データを維持する

これだけ頭に入れておけばコンテンツを編集しやすくなります。ありがとうございます！
