### ISSUE TITLE
Strange tag is showing in All tag list

### ISSUE THREAD

**Issue by ToruHagihara** [mozilla-japan/gitfab2#1245]
タグ一覧に以下の該当プロジェクトのないタグが含まれています。
{"smoke"=>nil}

<img width="489" alt="strange_tag" src="https://cloud.githubusercontent.com/assets/13010899/9926900/9aa38044-5d54-11e5-98c6-ad8e3b3cade2.png">

**Comment by oshimaryo** [comment]
報告ありがとうございます！
こちら対応しましたー

**Comment by ToruHagihara** [comment]
素早い対応ありがとうございます！
