### ISSUE TITLE
Display STL file with thumbnail through POV-Ray

### ISSUE THREAD

**Issue by oshimaryo** [mozilla-japan/gitfab2#1417]
#1303 は失敗したので、

- [x] upload時にSTLファイルはthumbnailを作成
 * thumbnail は重くなければAnimated GIF, 重かったらPNG
- [x] 作成後の表示ではthumbnailが表示される
 -> 別issue

- [x] クリックすると3Dモデルの表示

という風に実装しなおし

**Comment by oshimaryo** [comment]
STLからAnimated GIFを生成する処理が同期処理だと結構重いのでpngがマシかなぁ

**Comment by oshimaryo** [comment]
create時・update時の同期処理ではpngを返して、その裏で非同期にgifを作っておくのがいいかも

**Comment by dadaa** [comment]
一時的なイメージを渡す一方で非同期で処理に賛成

**Comment by oshimaryo** [comment]
その方向でやってみますー

**Comment by oshimaryo** [comment]
- [ ] `attachment.tmp` でpngを返す
- [ ] `attachment.thumb` でagifを返す
- [ ] `tmp`の生成は同期処理
- [ ] `thumb`の生成は非同期
- [ ] `thumb`ができるまでは`tmp`を返す

**Comment by oshimaryo** [comment]
deploy前に サーバに　`pov-ray` のインストールが必要
http://qiita.com/oshimaryo/items/ab5b3253c1591e8eafbf
