### ISSUE TITLE
We cannot attach any files in state editing dialog

### ISSUE THREAD

**Issue by ToruHagihara** [mozilla-japan/gitfab2#1426]
・State編集ダイアログ内で Material, Tool, Blueprint, Attachmentのすべてでファイル添付できない。

現象：
State編集ダイアログ内で添付ダイアログを表示
→ファイルを選択してsubmit
→リンクが作成されない。

環境：OS X 10.11.3
           Safari 9.0.3

**Comment by ToruHagihara** [comment]
素早い対応ありがとうございます。
現時点でまだ添付できないままですが、実環境への反映はタイムラグがありますか？

**Comment by oshimaryo** [comment]
@ToruHagihara 
報告ありがとうございます。
Firefoxでは起きないのですが、Safari/Chromeで起きるバグ（submitできない）のようです。
以下に別途 Issueを立てました。
下記 Issueが closeするまではお手数ですがFirefoxで作業いただけますと幸いです。
https://github.com/mozilla-japan/gitfab2/issues/1430
